name: Create new release

on:
  push:
    branches:
      - main

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Test available
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.repo;
            const branches = await github.rest.repos.listBranches(repo);
            
            const hasNewerReleaseBranch = await branches.data
              .filter(branch => branch.name.startsWith('releases/'))
              .some(async (branch) => {
                const comparison = await github.rest.repos.compareCommits({
                  ...repo,
                  base: branch.name,
                  head: process.env.GITHUB_SHA
                });
              
                return ["identical", "behind"].includes(comparison.data.status);
              });
            
            if (hasNewerReleaseBranch) {
              throw new Error("Newer releases branch detected!");
            }

      - name: Calculate new version
        if: success()
        id: calver
        run: |
          version=$(./scripts/get-new-version.sh)
          echo "new version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Create branch
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const ref = `refs/heads/releases/${process.env.version}`;
            const sha = context.sha;
            await github.rest.git.createRef({ owner, repo, ref, sha });
      
      - name: Checkout to new branch
        uses: actions/checkout@v3
        with:
          ref: releases/${{ env.version }}
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          npm pkg set version=${{ env.version }}
          git add package.json
          git commit -m "Update version to ${{ env.version }}"
          git push origin releases/${{ env.version }}

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = `releases/${process.env.version}`;
            const base = 'main';
            const title = `Release ${process.env.version}`
            await github.rest.pulls.create({ owner, repo, head, base, title });
