name: Create new release

on:
  push:
    branches:
      - main

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test available
        run: |
          ./scripts/test-release-available.sh $GITHUB_SHA

      - name: Calculate new version
        if: success()
        id: calver
        run: |
          version=$(./scripts/get-new-version.sh)
          echo "new version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Create branch
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const ref = `refs/heads/releases/${process.env.version}`;
            const sha = context.sha;
            await github.rest.git.createRef({ owner, repo, ref, sha });
      
      - name: Checkout to new branch
        uses: actions/checkout@v3
        with:
          ref: releases/$version

      - name: Update package.json version
        run: npm pkg set version=$version
          
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const path = 'package.json';
            
            const fs = require('fs');
            const updatedContent = fs.readFileSync(path, 'utf8');
            const encodedContent = Buffer.from(updatedContent).toString('base64');
            
            const fileContentResponse = await github.rest.repos.getContent({
              owner,
              repo,
              path
            });
            
            const currentSHA = fileContentResponse.data.sha;
            
            await github.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path,
              message: `Update version to ${process.env.version}`,
              content: encodedContent,
              sha: currentSHA
            });

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = `releases/${process.env.version}`;
            const base = 'main';
            await github.rest.pulls.create({ owner, repo, head, base });
