name: Create new release

on:
  push:
    branches:
      - main

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test available
        run: |
          ./scripts/test-release-available.sh $GITHUB_SHA

      - name: Calculate new version
        if: success()
        id: calver
        run: |
          version=$(./scripts/get-new-version.sh)
          echo "new version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Create branch
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const ref = `refs/heads/releases/${process.env.version}`;
            const sha = context.sha;
            await github.rest.git.createRef({ owner, repo, ref, sha });
      
      - name: Checkout to new branch
        uses: actions/checkout@v3
        with:
          ref: releases/${{ env.version }}
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          npm pkg set version=${{ env.version }}
          git add package.json
          git commit -m "Update version to ${{ env.version }}"
          git push origin releases/${{ env.version }}

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = `releases/${process.env.version}`;
            const base = 'main';
            const title = `Release ${process.env.version}`
            await github.rest.pulls.create({ owner, repo, head, base, title });
