name: Release to prod

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  tagging:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set next release version
        id: version
        run: |
          version=${GITHUB_HEAD_REF##releases/}
          echo "release version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

  cleanup:
    needs: tagging
    runs-on: ubuntu-latest
    steps:
      - name: Delete old release branches
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const currentVersion = process.env.GITHUB_HEAD_REF.slice("releases/".length).split('.').map(Number);
            const versionBranchPrefix = "releases/";

            const branches = await github.rest.repos.listBranches({
              owner,
              repo,
            });

            const releaseBranches = branches.data
              .filter(branch => branch.name.startsWith(versionBranchPrefix))
              .map(branch => ({ name: branch.name, version: branch.name.slice(versionBranchPrefix.length).split('.').map(Number)}));

            for (let {name, version: branchVersion} of releaseBranches) {
              if (branchVersion.some((val, i) => val < currentVersion[i])) {
                await github.rest.git.deleteRef({
                  owner,
                  repo,
                  ref: "heads/" + name,
                });
                console.log(`Deleted branch ${name}`);
              }
            }
  
